# ML Project 
### Rey Stone, Mara Backsen, Winter Russell

In [51]:
import pandas as pd
import numpy as np

In [52]:
covid = pd.read_csv('data/Covid Data.csv')
covid.info()
covid.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype 
---  ------                --------------    ----- 
 0   USMER                 1048575 non-null  int64 
 1   MEDICAL_UNIT          1048575 non-null  int64 
 2   SEX                   1048575 non-null  int64 
 3   PATIENT_TYPE          1048575 non-null  int64 
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64 
 6   PNEUMONIA             1048575 non-null  int64 
 7   AGE                   1048575 non-null  int64 
 8   PREGNANT              1048575 non-null  int64 
 9   DIABETES              1048575 non-null  int64 
 10  COPD                  1048575 non-null  int64 
 11  ASTHMA                1048575 non-null  int64 
 12  INMSUPR               1048575 non-null  int64 
 13  HIPERTENSION          1048575 non-null  int64 
 14  OTHER_DISEASE         1048575 non-null  int64 
 15

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE   DATE_DIED  INTUBED  PNEUMONIA  \
0      2             1    1             1  03/05/2020       97          1   
1      2             1    2             1  03/06/2020       97          1   
2      2             1    2             2  09/06/2020        1          2   
3      2             1    1             1  12/06/2020       97          2   
4      2             1    2             1  21/06/2020       97          2   

   AGE  PREGNANT  DIABETES  ...  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
0   65         2         2  ...       2        2             1              2   
1   72        97         2  ...       2        2             1              2   
2   55        97         1  ...       2        2             2              2   
3   53         2         2  ...       2        2             2              2   
4   68        97         1  ...       2        2             1              2   

   CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  ICU  
0               2        2              2        2                     3   97  
1               2        1              1        2                     5   97  
2               2        2              2        2                     3    2  
3               2        2              2        2                     7   97  
4               2        2              2        2                     3   97  

[5 rows x 21 columns]

In [65]:
#Removing all rows that contain missing data in binary columns
covid_clean = covid
cols = ['INTUBED', 'PNEUMONIA', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR', 'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY', 'RENAL_CHRONIC', 'TOBACCO', 'ICU', "PATIENT_TYPE"]
for col in cols:
    covid_clean = covid_clean[covid_clean[col] < 3]
covid_clean.info()

covid_clean["PATIENT_TYPE"].value_counts

<class 'pandas.core.frame.DataFrame'>
Index: 76832 entries, 5 to 1048569
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   USMER                 76832 non-null  int64 
 1   MEDICAL_UNIT          76832 non-null  int64 
 2   SEX                   76832 non-null  int64 
 3   PATIENT_TYPE          76832 non-null  int64 
 4   DATE_DIED             76832 non-null  object
 5   INTUBED               76832 non-null  int64 
 6   PNEUMONIA             76832 non-null  int64 
 7   AGE                   76832 non-null  int64 
 8   PREGNANT              76832 non-null  int64 
 9   DIABETES              76832 non-null  int64 
 10  COPD                  76832 non-null  int64 
 11  ASTHMA                76832 non-null  int64 
 12  INMSUPR               76832 non-null  int64 
 13  HIPERTENSION          76832 non-null  int64 
 14  OTHER_DISEASE         76832 non-null  int64 
 15  CARDIOVASCULAR        76832 non-null  i

<bound method IndexOpsMixin.value_counts of 5          2
8          2
9          2
16         2
56         2
          ..
1048535    2
1048553    2
1048554    2
1048567    2
1048569    2
Name: PATIENT_TYPE, Length: 76832, dtype: int64>

In [54]:
#Transforming DATE_DIED column into a binary column that just displays whether or not the patient died
covid_clean['PATIENT_DIED'] = np.where(covid_clean['DATE_DIED'] == '9999-99-99', 2, 1)
covid_clean_transform = covid_clean.drop('DATE_DIED', axis = 1)
covid_clean_transform['PATIENT_DIED'].value_counts()

PATIENT_DIED
2    52978
1    23854
Name: count, dtype: int64

In [55]:
covid_clean_transform.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76832 entries, 5 to 1048569
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   USMER                 76832 non-null  int64
 1   MEDICAL_UNIT          76832 non-null  int64
 2   SEX                   76832 non-null  int64
 3   PATIENT_TYPE          76832 non-null  int64
 4   INTUBED               76832 non-null  int64
 5   PNEUMONIA             76832 non-null  int64
 6   AGE                   76832 non-null  int64
 7   PREGNANT              76832 non-null  int64
 8   DIABETES              76832 non-null  int64
 9   COPD                  76832 non-null  int64
 10  ASTHMA                76832 non-null  int64
 11  INMSUPR               76832 non-null  int64
 12  HIPERTENSION          76832 non-null  int64
 13  OTHER_DISEASE         76832 non-null  int64
 14  CARDIOVASCULAR        76832 non-null  int64
 15  OBESITY               76832 non-null  int64
 16  RENAL_C

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [57]:
X = covid_clean_transform.drop(["PATIENT_TYPE", "PATIENT_DIED"], axis=1)
y = covid_clean_transform[["PATIENT_TYPE", "PATIENT_DIED"]]

In [58]:
X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)

In [ ]:

X = covid_clean_transform.drop(["PATIENT_DIED"], axis=1)
y = covid_clean_transform[["PATIENT_DIED"]]

X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)


from sklearn.ensemble import RandomForestClassifier   
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
model = RandomForestClassifier(
    n_estimators=1000,     
    max_depth=None,
    class_weight="balanced",     
    random_state=42
)
model.fit(X_train_bin, y_train_bin)
predictions = model.predict(X_test_bin)

print(f"Death accuracy: {accuracy_score(y_test_bin, predictions)}")
c_matrix = confusion_matrix(y_test_bin, predictions)
print(c_matrix)

from sklearn.metrics import classification_report

print(classification_report(y_test_bin, predictions))


importances = pd.DataFrame({
    'feature': X_train_bin.columns,
    'importance': model.feature_importances_
})

importances = importances.sort_values(by='importance', ascending=False)
print(importances)



c:\Users\mback\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Death accuracy: 0.7460737527114968
[[ 4241  2926]
 [ 2927 12956]]
              precision    recall  f1-score   support

           1       0.59      0.59      0.59      7167
           2       0.82      0.82      0.82     15883

    accuracy                           0.75     23050
   macro avg       0.70      0.70      0.70     23050
weighted avg       0.75      0.75      0.75     23050

                 feature  importance
6                    AGE    0.426548
4                INTUBED    0.158011
18  CLASIFFICATION_FINAL    0.090238
1           MEDICAL_UNIT    0.073765
5              PNEUMONIA    0.042798
12          HIPERTENSION    0.029013
8               DIABETES    0.026626
15               OBESITY    0.023907
0                  USMER    0.023476
13         OTHER_DISEASE    0.014978
19                   ICU    0.014015
16         RENAL_CHRONIC    0.013753
14        CARDIOVASCULAR    0.013274
11               INMSUPR    0.012235
9                   COPD    0.011919
17             

In [74]:
# accuracy and feature importance for max depth=10 : death

X = covid_clean_transform.drop(["PATIENT_DIED"], axis=1)
y = covid_clean_transform[["PATIENT_DIED"]]

X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)


from sklearn.ensemble import RandomForestClassifier   
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
!pip install imblearn
from imblearn.ensemble import BalancedRandomForestClassifier
model = BalancedRandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    random_state=42
)

model.fit(X_train_bin, y_train_bin)
predictions = model.predict(X_test_bin)

print(f"Death accuracy: {accuracy_score(y_test_bin, predictions)}")
c_matrix = confusion_matrix(y_test_bin, predictions)
print(c_matrix)

from sklearn.metrics import classification_report

print(classification_report(y_test_bin, predictions))


importances = pd.DataFrame({
    'feature': X_train_bin.columns,
    'importance': model.feature_importances_
})

importances = importances.sort_values(by='importance', ascending=False)
print(importances)




   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-learn]
   ---------------------------------------- 0/2 [imbalanced-l


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip
c:\Users\mback\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Death accuracy: 0.7356182212581345
[[ 4900  2267]
 [ 3827 12056]]
              precision    recall  f1-score   support

           1       0.56      0.68      0.62      7167
           2       0.84      0.76      0.80     15883

    accuracy                           0.74     23050
   macro avg       0.70      0.72      0.71     23050
weighted avg       0.75      0.74      0.74     23050

                 feature  importance
6                    AGE    0.427990
4                INTUBED    0.154982
18  CLASIFFICATION_FINAL    0.089706
1           MEDICAL_UNIT    0.073973
5              PNEUMONIA    0.042287
12          HIPERTENSION    0.029131
8               DIABETES    0.027393
15               OBESITY    0.023872
0                  USMER    0.023826
13         OTHER_DISEASE    0.015153
19                   ICU    0.014384
16         RENAL_CHRONIC    0.013827
14        CARDIOVASCULAR    0.013368
11               INMSUPR    0.012324
9                   COPD    0.012234
17             

In [61]:
# accuracy and feature importance for max depth = 10 : ICU

X = covid_clean_transform.drop(["ICU"], axis=1)
y = covid_clean_transform[["ICU"]]

X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)


from sklearn.ensemble import RandomForestClassifier   
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
model = RandomForestClassifier(
    n_estimators=1000,     
    max_depth=10,        
    random_state=42
)
model.fit(X_train_bin, y_train_bin)
predictions = model.predict(X_test_bin)

print(f"ICU accuracy: {accuracy_score(y_test_bin, predictions)}")
c_matrix = confusion_matrix(y_test_bin, predictions)
print(c_matrix)

importances = pd.DataFrame({
    'feature': X_train_bin.columns,
    'importance': model.feature_importances_
})

importances = importances.sort_values(by='importance', ascending=False)
print(importances)



c:\Users\mback\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


ICU accuracy: 0.9303253796095444
[[  258  1514]
 [   92 21186]]
                 feature  importance
4                INTUBED    0.374136
1           MEDICAL_UNIT    0.276552
6                    AGE    0.117282
5              PNEUMONIA    0.053511
19          PATIENT_DIED    0.039898
18  CLASIFFICATION_FINAL    0.028984
0                  USMER    0.019042
13         OTHER_DISEASE    0.010590
15               OBESITY    0.010443
12          HIPERTENSION    0.009455
7               PREGNANT    0.009141
14        CARDIOVASCULAR    0.009028
11               INMSUPR    0.008731
8               DIABETES    0.008573
16         RENAL_CHRONIC    0.007027
17               TOBACCO    0.006152
10                ASTHMA    0.005855
9                   COPD    0.005599
3           PATIENT_TYPE    0.000000
2                    SEX    0.000000


In [66]:
X = covid_clean_transform.drop(["PATIENT_DIED", "INTUBED"], axis=1)
y = covid_clean_transform[["PATIENT_DIED"]]

X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)


from sklearn.ensemble import RandomForestClassifier   
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
model = RandomForestClassifier(
    n_estimators=1000,     
    max_depth=10,        
    random_state=42
)
model.fit(X_train_bin, y_train_bin)
predictions = model.predict(X_test_bin)

print(f"ICU accuracy: {accuracy_score(y_test_bin, predictions)}")
c_matrix = confusion_matrix(y_test_bin, predictions)
print(c_matrix)

importances = pd.DataFrame({
    'feature': X_train_bin.columns,
    'importance': model.feature_importances_
})

importances = importances.sort_values(by='importance', ascending=False)
print(importances)



c:\Users\mback\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


ICU accuracy: 0.7442082429501085
[[ 2671  4496]
 [ 1400 14483]]
                 feature  importance
5                    AGE    0.368046
17  CLASIFFICATION_FINAL    0.195282
4              PNEUMONIA    0.133556
1           MEDICAL_UNIT    0.081673
11          HIPERTENSION    0.056167
7               DIABETES    0.042472
18                   ICU    0.031187
15         RENAL_CHRONIC    0.015975
0                  USMER    0.014680
14               OBESITY    0.010050
12         OTHER_DISEASE    0.008444
6               PREGNANT    0.008092
10               INMSUPR    0.007810
13        CARDIOVASCULAR    0.007589
8                   COPD    0.007376
16               TOBACCO    0.006143
9                 ASTHMA    0.005458
2                    SEX    0.000000
3           PATIENT_TYPE    0.000000


In [67]:
# ICU prediction without intubed

X = covid_clean_transform.drop(["ICU", "INTUBED"], axis=1)
y = covid_clean_transform[["ICU"]]

X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)


from sklearn.ensemble import RandomForestClassifier   
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
model = RandomForestClassifier(
    n_estimators=1000,     
    max_depth=10,        
    random_state=42
)
model.fit(X_train_bin, y_train_bin)
predictions = model.predict(X_test_bin)

print(f"ICU accuracy: {accuracy_score(y_test_bin, predictions)}")
c_matrix = confusion_matrix(y_test_bin, predictions)
print(c_matrix)

importances = pd.DataFrame({
    'feature': X_train_bin.columns,
    'importance': model.feature_importances_
})

importances = importances.sort_values(by='importance', ascending=False)
print(importances)



c:\Users\mback\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


ICU accuracy: 0.9232104121475054
[[   13  1759]
 [   11 21267]]
                 feature  importance
1           MEDICAL_UNIT    0.351929
5                    AGE    0.206071
4              PNEUMONIA    0.118317
18          PATIENT_DIED    0.093338
17  CLASIFFICATION_FINAL    0.042230
0                  USMER    0.034944
12         OTHER_DISEASE    0.020597
14               OBESITY    0.017398
10               INMSUPR    0.016320
13        CARDIOVASCULAR    0.015721
11          HIPERTENSION    0.014986
7               DIABETES    0.014260
6               PREGNANT    0.013567
15         RENAL_CHRONIC    0.012619
16               TOBACCO    0.010720
9                 ASTHMA    0.008541
8                   COPD    0.008442
2                    SEX    0.000000
3           PATIENT_TYPE    0.000000


In [ ]:
#Predicting intubed

X = covid_clean_transform.drop(["INTUBED"], axis=1)
y = covid_clean_transform[["INTUBED"]]

X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)


from sklearn.ensemble import RandomForestClassifier   
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
model = RandomForestClassifier(
    n_estimators=1000,     
    max_depth=10,        
    random_state=42
)
model.fit(X_train_bin, y_train_bin)
predictions = model.predict(X_test_bin)

print(f"Intubed accuracy: {accuracy_score(y_test_bin, predictions)}")
c_matrix = confusion_matrix(y_test_bin, predictions)
print(c_matrix)

importances = pd.DataFrame({
    'feature': X_train_bin.columns,
    'importance': model.feature_importances_
})

importances = importances.sort_values(by='importance', ascending=False)
print(importances)



c:\Users\mback\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


ICU accuracy: 0.864295010845987
[[  569  2927]
 [  201 19353]]
                 feature  importance
19          PATIENT_DIED    0.474318
18                   ICU    0.228306
5                    AGE    0.068261
1           MEDICAL_UNIT    0.063254
17  CLASIFFICATION_FINAL    0.048103
4              PNEUMONIA    0.043654
0                  USMER    0.009332
11          HIPERTENSION    0.008552
14               OBESITY    0.007853
7               DIABETES    0.007817
12         OTHER_DISEASE    0.006674
13        CARDIOVASCULAR    0.006096
15         RENAL_CHRONIC    0.005976
10               INMSUPR    0.005174
8                   COPD    0.005100
16               TOBACCO    0.005054
9                 ASTHMA    0.004181
6               PREGNANT    0.002294
3           PATIENT_TYPE    0.000000
2                    SEX    0.000000


In [69]:
#Predicting intubed without ICU or died

X = covid_clean_transform.drop(["INTUBED", "PATIENT_DIED", "ICU"], axis=1)
y = covid_clean_transform[["INTUBED"]]

X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(X, y, test_size = 0.3, random_state=42)


from sklearn.ensemble import RandomForestClassifier   
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
model = RandomForestClassifier(
    n_estimators=1000,     
    max_depth=10,        
    random_state=42
)
model.fit(X_train_bin, y_train_bin)
predictions = model.predict(X_test_bin)

print(f"Intubed accuracy: {accuracy_score(y_test_bin, predictions)}")
c_matrix = confusion_matrix(y_test_bin, predictions)
print(c_matrix)

importances = pd.DataFrame({
    'feature': X_train_bin.columns,
    'importance': model.feature_importances_
})

importances = importances.sort_values(by='importance', ascending=False)
print(importances)



c:\Users\mback\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Intubed accuracy: 0.8483731019522777
[[    1  3495]
 [    0 19554]]
                 feature  importance
5                    AGE    0.237988
4              PNEUMONIA    0.210544
17  CLASIFFICATION_FINAL    0.184185
1           MEDICAL_UNIT    0.144052
11          HIPERTENSION    0.029949
7               DIABETES    0.025798
0                  USMER    0.024006
14               OBESITY    0.022715
12         OTHER_DISEASE    0.021008
15         RENAL_CHRONIC    0.017801
13        CARDIOVASCULAR    0.017613
10               INMSUPR    0.017142
16               TOBACCO    0.014329
8                   COPD    0.013745
9                 ASTHMA    0.012535
6               PREGNANT    0.006587
3           PATIENT_TYPE    0.000000
2                    SEX    0.000000
